name: Quality

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v3 

      - name: Tidy
        working-directory: builder
        run: go mod tidy

      - name: Install dependencies
        working-directory: builder
        run: go mod download
    
      - name: Create .test.env file
        working-directory: builder
        run: |
          echo "ENVIRONMENT=cicd" > .test.env
          echo "LOG_LEVEL=debug" >> .test.env
          echo "LOG_WRITE_TO_FILE=false" >> .test.env
          echo "DB_FILE=${{ github.workspace }}/cicd.db" >> .test.env
          echo "FIREBASE_SECRET=${{ secrets.FIREBASE_SECRET }}" >> .test.env
          echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> .test.env
          echo "UPLOADER_MAX_SIZE=5000" >> .test.env
          echo "UPLOADER_AUTHENTICATE=true" >> .test.env
          echo "UPLOADER_SUPPORTED_MIME_TYPES=* >> .test.env
          echo "UPLOADER_FOLDER=${{ github.workspace }}/test_output" >> .test.env
          echo "STORE_TYPE=local" >> .test.env
          echo "AWS_BUCKET={{ secrets.AWS_BUCKET }}" >> .test.env
          echo "AWS_SECRET_ACCESS_KEY={{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .test.env
          echo "AWS_REGION={{ secrets.AWS_REGION }}" >> .test.env
          echo "AWS_ACCESS_KEY_ID={{ secrets.AWS_ACCESS_KEY_ID }}" >> .test.env
          echo "STATIC_PATH=static" >> .test.env 
          echo "BASE_URL=http://localhost" >> .test.env

      - name: Run tests
        working-directory: builder
        run: go test -v -race -covermode atomic -coverprofile=covprofile ./...
        if: always()

      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: Send coverage
        working-directory: builder
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: $HOME/go/bin/goveralls -coverprofile=covprofile -service=github

      - name: Upload test artifacts (optional)
        uses: actions/upload-artifact@v3
        if: failure() 
        with:
          name: test-results
          path: ${{ github.workspace }}/

      - name: Fail workflow on test failures (optional)
        uses: styfle/cancel-workflow-action@0.8.0 
        if: failure()  
        with:
          message: 'Tests failed. Fix the errors before merging...'