name: Test Suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v3 

      - name: Tidy
        working-directory: builder
        run: go mod tidy

      - name: Install dependencies
        working-directory: builder
        run: go mod download
    
      - name: Create config.yaml file
        working-directory: builder
        run: |
          echo "environment: cicd" > config.yaml
          echo "logLevel: debug" >> config.yaml
          echo "logWriteToFile: false" >> config.yaml
          echo "dbFile: ${{ github.workspace }}/cicd.db" >> config.yaml
          echo "firebaseSecret: ${{ secrets.FIREBASE_SECRET }}" >> config.yaml

      - name: Run tests
        working-directory: builder
        run: go test -v ./...
        if: always()

      - name: Upload test artifacts (optional)
        uses: actions/upload-artifact@v3
        if: failure() 
        with:
          name: test-results
          path: ${{ github.workspace }}/

      - name: Fail workflow on test failures (optional)
        uses: styfle/cancel-workflow-action@0.8.0 
        if: failure()  
        with:
          message: 'Tests failed. Fix the errors before merging...'