name: Quality

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest 

    env:
      APP_NAME: test
      ENVIRONMENT: test
      LOG_LEVEL: debug
      LOG_WRITE_TO_FILE: false
      DB_FILE: ${{ github.workspace }}/cicd.db
      FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      UPLOADER_MAX_SIZE: 5000
      UPLOADER_AUTHENTICATE: true
      UPLOADER_SUPPORTED_MIME_TYPES: "*"
      UPLOADER_FOLDER: ${{ github.workspace }}/test_output
      STORE_TYPE: local
      AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      STATIC_PATH: static
      BASE_URL: http://localhost

    steps:
      - uses: actions/checkout@v3 

      - name: Tidy
        working-directory: builder
        run: go mod tidy

      - name: Install dependencies
        working-directory: builder
        run: go mod download
    
      - name: Run tests
        working-directory: builder
        run: go test -v -race -covermode atomic -coverprofile=covprofile ./...
        if: always()

      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: Send coverage
        working-directory: builder
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: $HOME/go/bin/goveralls -coverprofile=covprofile -service=github

      - name: Upload test artifacts (optional)
        uses: actions/upload-artifact@v3
        if: failure() 
        with:
          name: test-results
          path: ${{ github.workspace }}/

      - name: Fail workflow on test failures (optional)
        uses: styfle/cancel-workflow-action@0.8.0 
        if: failure()  
        with:
          message: 'Tests failed. Fix the errors before merging...'